//
//  WelcomeRouter.swift
//
//  Created by Admin on 8/19/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WelcomeRoutingLogic {
    func routeToRegistration()
}

protocol WelcomeDataPassing {
    var dataStore: WelcomeDataStore? { get }
}

final class WelcomeRouter: NSObject, WelcomeDataPassing {
    
    //  MARK:- Clean Components
    weak var viewController: WelcomeViewController?
    var dataStore: WelcomeDataStore?
}

extension WelcomeRouter: WelcomeRoutingLogic {
    
    //  MARK: Routing
    func routeToRegistration() {
        guard let destinationVC = UIStoryboard.init(name: "Main", bundle: nil)
                .instantiateViewController(withIdentifier: RegistrationViewController.identifier)
                as? RegistrationViewController else { return }
        
        guard var destinationDS = destinationVC.router?.dataStore,
              let dataStore = dataStore,
              let viewController = viewController
        else { return }
        passDataToRegistration(source: dataStore, destination: &destinationDS)
        navigateToRegistrationPage(source: viewController, destination: destinationVC)
    }
    
    //  MARK: Navigation
    private func navigateToRegistrationPage(source: WelcomeViewController, destination: UIViewController) {
        source.show(destination, sender: nil)
    }
    
    //  MARK: Passing data
    private func passDataToRegistration(source: WelcomeDataStore, destination: inout RegistationDataStore) {
        destination.tag = source.identifier
    }
}
