//
//  WelcomeModels.swift
//  Netflix
//
//  Created by Admin on 8/19/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Welcome {
    
  // MARK: Use cases
  enum Save {
    
    struct Request {
        var buttonTag: Int
    }
    
    struct Response {}
    
    struct ViewModel {}
  }
}
