//
//  WelcomeViewController.swift
//  Netflix
//
//  Created by Admin on 8/19/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WelcomeDisplayLogic: AnyObject {}

final class WelcomeViewController: BackgroundViewControlller , WelcomeDisplayLogic {
    
    //  MARK:- Clean Components
    var interactor: WelcomeBusinessLogic?
    var router: (NSObjectProtocol & WelcomeRoutingLogic & WelcomeDataPassing)?
    
    //  MARK: @IBOutlet
    @IBOutlet weak var sigInBtn: UIButton! {
        didSet {
            sigInBtn.tintColor = Constants.Design.Color.Primary.White
        }
    }
    @IBOutlet weak var getStaredBtn: UIButton! {
        didSet {
            getStaredBtn.layer.backgroundColor = UIColor(red: 0.824, green: 0.184, blue: 0.149, alpha: 1).cgColor
            getStaredBtn.layer.cornerRadius = 2
            getStaredBtn.tintColor = Constants.Design.Color.Primary.White
            getStaredBtn.titleLabel?.font = Constants.Design.Font.HeadingTwo
        }
    }
    @IBOutlet weak var titleLb: UILabel! {
        didSet {
            titleLb.textColor = Constants.Design.Color.Primary.White
            titleLb.font = UIFont(name: "Helvetica Neue", size: 32)
            titleLb.textAlignment = .center
        }
    }
    @IBOutlet weak var sublineLb: UILabel! {
        didSet {
            sublineLb.textColor = Constants.Design.Color.Primary.White
            sublineLb.font = UIFont(name: "Helvetica Neue", size: 18)
            sublineLb.textAlignment = .center
        }
    }
    
    //  MARK: Object lifecycle
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    //  MARK: View lifecycle
    override func viewWillAppear(_ animated: Bool) {
        super .viewWillAppear(true)
        navigationController?.navigationBar.isHidden = true
    }
    
    //  MARK: Setup
    private func setup() {
        let viewController = self
        let presenter = WelcomePresenter()
        let interactor = WelcomeInteractor()
        let router = WelcomeRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    //  MARK:- Button Action
    @IBAction func moveToRegitrationPage(_ sender: Any) {
        guard let tag = (sender as? UIButton)?.tag else { return }
        interactor?.getTappeddButtonTag(requset: Welcome.Save.Request(buttonTag: tag))
        router?.routeToRegistration()
    }
}

