//
//  MoviesCollectionPresenter.swift
//  Netflix
//
//  Created by Admin on 8/29/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MoviesCollectionPresentationLogic
{
  func presentSomething(response: MoviesCollection.Something.Response)
}

class MoviesCollectionPresenter: MoviesCollectionPresentationLogic
{
  weak var viewController: MoviesCollectionDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: MoviesCollection.Something.Response)
  {
    let viewModel = MoviesCollection.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}

