//
//  RegistationModels.swift
//  Netflix
//
//  Created by Admin on 8/19/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Registation {
    
    struct UserInfo {
        var firstName: String
        var lastName: String
        var email: String
        var password: String
        var seenMoviesId: [Int] = []
    }
    struct SignInDetail {
        var email: String
        var password: String
    }
    
    struct RegistratioFormField {
        var name: String
        var lastName: String
        var email: String
        var password: String
        var confirmedPassword: String
    }
    
    enum ErrorMessage: String {
        case allFieldError = "Please fill in all fields"
        case emailError = "Email is not valid"
        case passwordError = "This password is not secure\n The password must be at least 8 characters long and must contain an uppercase Latin letter and a number"
        case passowrdNotConfirmd = "Passwords doesn't match"
    }
    
    // MARK: Use cases
    enum UserData {
        struct Request {
            var userInfo: UserInfo
        }
        struct Response {
            var errorMessage: String?
        }
        struct ViewModel {
            var errorMessage: String?
        }
    }
    
    enum SigInUser {
        struct Request {
            var detail: SignInDetail
        }
        struct Response {
            var errorMessage: String?
        }
        struct ViewModel {
            var errorMessage: String?
        }
    }
    
    enum CheckData {
        struct Request {
            var registrationFormField: RegistratioFormField
        }
        struct Response {
            var message: ErrorMessage?
        }
        struct ViewModel {
            var errorMessage: String?
        }
    }
    
    enum ViewItemVisibility {
        struct Request {
            var tagId: Int?
        }
        struct Response {
            var visibility: Bool
            var id: Int
        }
        struct ViewModel {
            var textFieldVisibility: Bool
            var selectedSegmentId: Int
        }
    }
}
