//
//  RegistationPresenter.swift
//  Netflix
//
//  Created by Admin on 8/19/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RegistationPresentationLogic {
    func presentSomething(response: Registation.ViewItemVisibility.Response)
    func presentUserRegistrationAlertMessage(response: Registation.CheckData.Response)
    func presentUserCreationAlertMessage(response: Registation.UserData.Response)
    func presentSignAlertMessage(response: Registation.SigInUser.Response)
    
}

final class RegistationPresenter: RegistationPresentationLogic {
    weak var viewController: RegistationDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Registation.ViewItemVisibility.Response) {
        let viewModel = Registation.ViewItemVisibility.ViewModel(textFieldVisibility: response.visibility, selectedSegmentId: response.id)
        viewController?.displayViewWithConfig(viewModel: viewModel)
    }
    
    func presentUserRegistrationAlertMessage(response: Registation.CheckData.Response) {
        let viewModel = Registation.CheckData.ViewModel(errorMessage: response.message?.rawValue)
        viewController?.displayUserRegistratonAlert(viewModel: viewModel)
    }
    
    func presentUserCreationAlertMessage(response: Registation.UserData.Response) {
        let viewModel = Registation.UserData.ViewModel(errorMessage: response.errorMessage)
        viewController?.displayUserCreationAlert(viewModel: viewModel)
    }
    
    func presentSignAlertMessage(response: Registation.SigInUser.Response) {
        let viewModel = Registation.SigInUser.ViewModel(errorMessage: response.errorMessage)
        viewController?.displaySigInAlert(viewModel: viewModel)
    }
    
}
