//  ComingSoonRouter.swift
//  
//  Created by Admin on 9/2/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com

import UIKit

protocol ComingSoonRoutingLogic {
    func routeToDetailsVc()
}

protocol ComingSoonDataPassing {
    var dataStore: ComingSoonDataStore? { get }
}

final class ComingSoonRouter: NSObject, ComingSoonDataPassing {
    weak var viewController: ComingSoonViewController?
    var dataStore: ComingSoonDataStore?
    
}
extension ComingSoonRouter: ComingSoonRoutingLogic {
    
    //  MARK: Routing
    func routeToDetailsVc() {
        let destinationVC = DetailsViewController()
        destinationVC.modalPresentationStyle = .fullScreen
        guard var destinationDS = destinationVC.router?.dataStore,
              let dataStore = dataStore,
              let viewController = viewController
        else { return }
        passDataToSomewhere(source: dataStore, destination: &destinationDS)
        navigateToTrailerVC(source: viewController, destination: destinationVC)
    }
    
    //  MARK: Navigation
    private func navigateToTrailerVC(source: ComingSoonViewController, destination: UIViewController) {
        source.present(destination, animated: true, completion: nil)
    }
    
    //  MARK: Passing data
    private func passDataToSomewhere(source: ComingSoonDataStore, destination: inout DetailsDataStore) {
        destination.movieId = source.selectedMovieId
    }
}
