//
//  MovieTrailerPresenter.swift
//  Netflix
//
//  Created by Admin on 9/5/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieTrailerPresentationLogic {
    func presentMovieTrailer(response: MovieTrailer.GetTrailer.Response)
}

final class MovieTrailerPresenter: MovieTrailerPresentationLogic {
    weak var viewController: MovieTrailerDisplayLogic?
    
    //  MARK: Present Movie Trailer
    func presentMovieTrailer(response: MovieTrailer.GetTrailer.Response) {
        guard response.error == nil else {
            viewController?.displayAlert(viewModel: MovieTrailer.Error.ViewModel(errorModel: ErrorViewModel(title: AlerTitle.Error.error, message: response.error!.rawValue)))
            return
        }
        let trailerViewModel = TrailerViewModel(movieTitle: response.title, overview: response.overView, youtubeId: response.youtubeId)
        let viewModel = MovieTrailer.GetTrailer.ViewModel(trailer: trailerViewModel)
        viewController?.displayMovieTrailer(viewModel: viewModel)
    }
}
