//
//  DetailsModels.swift
//  Netflix
//
//  Created by Admin on 9/8/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Details {
    
    // MARK: Use cases
    enum GetError {
        struct Request{}
        
        struct Response {
            var error: Error
        }
        
        struct ViewModel {
            var errorModel: ErrorViewModel
        }
    }

    enum GetMovie {
        
        struct Request { }
        struct Response {
            var error: APICollerError?
            var movie: MovieDetails?
        }
        struct ViewModel {
            var movieViewModel: MovieViewModel
        }
    }
    
    enum UpdateUserData {
        struct Request {
            var movieId: Int
        }
        struct Response {}
        
        struct ViewModel {}
        
    }
}
