//
//  BottomSheetRouter.swift
//  
//
//  Created by Admin on 9/16/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BottomSheetRoutingLogic {
    func routeBack()
}

protocol BottomSheetDataPassing {
    var dataStore: BottomSheetDataStore? { get }
}

final class BottomSheetRouter: NSObject, BottomSheetDataPassing {
    weak var viewController: BottomSheetViewController?
    var dataStore: BottomSheetDataStore?
}

//  MARK:- BottomSheetRoutingLogic Methods
extension BottomSheetRouter:  BottomSheetRoutingLogic {
    
    //  MARK:- Route
    func routeBack() {
        self.viewController?.dismiss(animated: true, completion: nil)
        dismiss(source: viewController!)
    }
    
    //  MARK:- Navigate
    private func dismiss(source: BottomSheetViewController) {
        source.dismiss(animated: true, completion: nil)
    }
}
