//
//  BottomSheetInteractor.swift
//  
//
//  Created by Admin on 9/16/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BottomSheetBusinessLogic {}

protocol BottomSheetDataStore {
    //var name: String { get set }
}

final class BottomSheetInteractor: BottomSheetBusinessLogic, BottomSheetDataStore {
    var presenter: BottomSheetPresentationLogic?
    var worker: BottomSheetWorker?
}
