//
//  WatchedListWorker.swift
//  Netflix
//
//  Created by Admin on 9/7/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import FirebaseAuth

class WatchedListWorke {
    
//    func getSigInUserData(compilition: @escaping (UserData) -> Void) {
//        guard let currentUser = Auth.auth().currentUser else { return }
//        UserManger.shared.getUserData(by: currentUser.uid) {  userData in
//            compilition(userData)
//        }
//    }
}
