//
//  ComingSoonInteractor.swift
//  Netflix
//
//  Created by Admin on 9/2/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ComingSoonBusinessLogic {
    func getUpcomingMovies(request: ComingSoon.GetUpcomingMovies.Request)
    func didTapMovie(requset: ComingSoon.MovieDetail.Request)
}

protocol ComingSoonDataStore {
    var movieDetails: Details { get set }
}

class ComingSoonInteractor: ComingSoonBusinessLogic, ComingSoonDataStore {
    
    var presenter: ComingSoonPresentationLogic?
    var worker: APIWoker?
    private var fetchedMovies = Movies(details: [])
    var movieDetails = Details()
    
    // MARK: Do something
    
    func getUpcomingMovies(request: ComingSoon.GetUpcomingMovies.Request) {
        worker = APIWoker()
        let url = API.dictionariOfAPI["Upcoming movies"]!
        worker?.fetchMoviesDetails(url: url, completion: { [weak self] (result: Result<Movies, APICollerError>) in
            var response = ComingSoon.GetUpcomingMovies.Response()
            switch result {
            case .success(let upcomingMovies):
                self?.fetchedMovies = upcomingMovies
                response.movies = upcomingMovies
            case .failure(let error):
                response.error = error
            }
            self?.presenter?.presentUpcomingMovies(response: response)
        })
    }

    func didTapMovie(requset: ComingSoon.MovieDetail.Request) {
        movieDetails = fetchedMovies.details.filter { $0.id! == requset.selectedMovieId }[0]
        presenter?.presentSelectedMovie(response: ComingSoon.MovieDetail.Response())
    }
}
