//
//  SearchMovieRouter.swift
//  Netflix
//
//  Created by Admin on 9/5/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SearchMovieRoutingLogic {
    func routeToTrailerVC(segue: UIStoryboardSegue?)
    func routeToSearcheResulte(segue: UIStoryboardSegue?)
}

protocol SearchMovieDataPassing {
    var dataStore: SearchMovieDataStore? { get }
}

class SearchMovieRouter: NSObject, SearchMovieRoutingLogic, SearchMovieDataPassing {
    
    weak var viewController: SearchMovieViewController?
    var dataStore: SearchMovieDataStore?
    
    // MARK: Routing
    
    
    func routeToTrailerVC(segue: UIStoryboardSegue?) {
        let destinationVC = MovieTrailerViewController()
        var destinationDS = destinationVC.router!.dataStore!
        passDataToSomewhere(source: dataStore!, destination: &destinationDS)
        navigateToTrailerVC(source: viewController!, destination: destinationVC)
    }
    
    // MARK: Navigation
    
    func navigateToTrailerVC(source: SearchMovieViewController, destination: UIViewController) {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func routeToSearcheResulte(segue: UIStoryboardSegue?) {
        guard let destinationVC = viewController?.searchController.searchResultsController as? SearchResultViewController else { return }
        var destinationDS = destinationVC.router!.dataStore!
        passSearchedData(source: dataStore!, destination: &destinationDS)
//        destinationVC.searchResultCollectionView.reloadData()
        destinationVC.searchResultIsUpdated.toggle()
        
    }

    func passSearchedData(source: SearchMovieDataStore, destination: inout SearchResultDataStore) {
        destination.searchedMovies = source.searchedMovies
    }

    func passDataToSomewhere(source: SearchMovieDataStore, destination: inout MovieTrailerDataStore) {
        destination.movieDetails = source.selectedMovieDetails
    }
    
    //func routeToSomewhere(segue: UIStoryboardSegue?)
    //{
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    //}
    
    // MARK: Navigation
    
    //func navigateToSomewhere(source: SearchMovieViewController, destination: SomewhereViewController)
    //{
    //  source.show(destination, sender: nil)
    //}
    
    // MARK: Passing data
    
    //func passDataToSomewhere(source: SearchMovieDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
