//
//  ProfilePresenter.swift
//  Netflix
//
//  Created by Admin on 9/16/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProfilePresentationLogic {
  func presentUserDetails(response: Profile.GetUserData.Response)
}

final class ProfilePresenter: ProfilePresentationLogic {
  weak var viewController: ProfileDisplayLogic?
  
  // MARK: Do something
  
  func presentUserDetails(response: Profile.GetUserData.Response) {
    let viewModel = Profile.GetUserData.ViewModel(profileModel: ProfileViewModel(with: response.userData))
    viewController?.displayUserDetails(viewModel: viewModel)
  }
}
