//
//  HomeRouter.swift
//  Netflix
//
//  Created by Admin on 8/22/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeRoutingLogic {
    func routeToProfile()
    func routToDetailsVc()
}

protocol HomeDataPassing {
    var dataStore: HomeDataStore? { get }
}

final class HomeRouter: NSObject, HomeDataPassing {
    weak var viewController: HomeViewController?
    var dataStore: HomeDataStore?
}

extension HomeRouter: HomeRoutingLogic {
    
    //  MARK: Routing
    func routeToProfile() {
        let destinationVC = ProfileViewController()
        present(destination: destinationVC)
    }
    
    
    func routToDetailsVc() {
        let destinationVC = DetailsViewController()
        destinationVC.modalPresentationStyle = .fullScreen
        guard var destinationDS = destinationVC.router?.dataStore,
              let dataStore = dataStore
        else { return }
        passDataToDetailsVc(source: dataStore, destination: &destinationDS)
        present(destination: destinationVC)
    }
    
    //  MARK: Navigation
    private func navigate(source: HomeViewController, destination: UIViewController) {
        source.navigationController?.pushViewController(destination, animated: true)
    }
    private func present(destination: UIViewController) {
        self.viewController?.present(destination, animated: true, completion: nil)
    }
    
    //  MARK: Passing data
    private func passDataToDetailsVc(source: HomeDataStore, destination: inout DetailsDataStore) {
        destination.movieId = source.selectedMovieId
    }
}
