//
//  HomeModels.swift
//  
//
//  Created by Admin on 8/22/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home {
    
    // MARK: Use cases
    enum Error {
        struct Request{}
        
        struct Response {}
        
        struct ViewModel {
            var errorModel: ErrorViewModel
        }
    }
    
    enum GetCurrentUserAccaunt {
        struct Request {}
        struct Response {
            let profileImage: UIImage
        }
        struct ViewModel {
            var image: UIImage
        }

    }

    enum MovieInfo {
        struct Request {
            var section: Int
            var sectionTitle: String
        }
        struct Response {
            var error: APICollerError?
            var section: Int
            
            var movies: Movies?
        }
        struct ViewModel {
            var section: Int
            var movies: [MovieViewModel]?
        }
    }
    
    enum GetSelectedMovie {
        struct Request{
            var selectedMovieId: Int
        }
        
        struct Response {}
        
        struct ViewModel {}
    }
}

