//
//  ProfilePresenter.swift
//  
//
//  Created by Admin on 9/16/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProfilePresentationLogic {
    func presentUserDetails(response: Profile.GetUserData.Response)
    func presentProfileImage(response: Profile.UpdateProfileImage.Response)
    func presentSaveError(response: Profile.SaveProfileImage.Response)
}

final class ProfilePresenter {
    weak var viewController: ProfileDisplayLogic?
}

extension ProfilePresenter: ProfilePresentationLogic {
    
    //  MARK: ProfilePresentationLogic metods
    func presentUserDetails(response: Profile.GetUserData.Response) {
        let viewModel = Profile.GetUserData.ViewModel(profileModel: ProfileViewModel(with: response.userData))
        viewController?.displayUserDetails(viewModel: viewModel)
    }
    func presentSaveError(response: Profile.SaveProfileImage.Response) {
        guard response.error != nil else { return }
        viewController?.dispalyAler(viewModel: Profile.GetError.ViewModel(errorModel: ErrorViewModel(title: AlerTitle.Error.error, message: response.error!.localizedDescription)))
    }
    
    func presentProfileImage(response: Profile.UpdateProfileImage.Response) {
        viewController?.dispalUpdatedProfileImage(viewModel: Profile.UpdateProfileImage.ViewModel(profileImage: response.image))
    }
}

