//
//  ProfileRouter.swift
//  Netflix
//
//  Created by Admin on 9/16/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProfileRoutingLogic {
    func routeBack()
    func routeToBottomSheet()
}

protocol ProfileDataPassing {
    var dataStore: ProfileDataStore? { get }
}

final class ProfileRouter: NSObject, ProfileDataPassing {
    weak var viewController: ProfileViewController?
    var dataStore: ProfileDataStore?
}

extension ProfileRouter: ProfileRoutingLogic {
    
    //  MARK:- Routing
    func routeToBottomSheet() {
        let destinationVC = BottomSheetViewController()
        guard let viewController = viewController else { return }
        present(source: viewController, destination: destinationVC)
    }
    func routeBack() {
        dissmisProfile()
    }
    
    //  MARK:- Navigation
    private func present(source: ProfileViewController, destination: UIViewController) {
        source.present(destination, animated: true, completion: nil)
    }
    private func dissmisProfile() {
        self.viewController?.dismiss(animated: false, completion: nil)
    }
}
