//
//  ProfileRouter.swift
//  Netflix
//
//  Created by Admin on 9/16/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProfileRoutingLogic {
    func routeBack(segue: UIStoryboardSegue?)
    func routeToBottomSheet(segue: UIStoryboardSegue?)
}

protocol ProfileDataPassing {
    var dataStore: ProfileDataStore? { get }
}

final class ProfileRouter: NSObject, ProfileDataPassing {
    weak var viewController: ProfileViewController?
    var dataStore: ProfileDataStore?
}

extension ProfileRouter: ProfileRoutingLogic {
    
    //  MARK:- Routing
    func routeToBottomSheet(segue: UIStoryboardSegue?) {
        let destinationVC = BottomSheetViewController()
        present(source: viewController!, destination: destinationVC)
    }
    func routeBack(segue: UIStoryboardSegue?) {
        dissmisProfile(source: viewController!)
    }
    
    //  MARK:- Navigation
    private func present(source: ProfileViewController, destination: UIViewController) {
        source.present(destination, animated: true, completion: nil)
    }
    private func dissmisProfile(source: ProfileViewController) {
        source.dismiss(animated: false, completion: nil)
    }
}
