//
//  ProfileModels.swift
//  Netflix
//
//  Created by Admin on 9/16/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Profile {
    
    // MARK: Use cases
    
    enum GetError {
        struct Request{}
        
        struct Response {}
        
        struct ViewModel {
            var errorModel: ErrorViewModel
        }
    }

    enum GetUserData {
        struct Request{}
        struct Response {
            var userData: UserData
        }
        struct ViewModel {
            var profileModel: ProfileViewModel
        }
    }
    
    enum UpdateProfileImage {
        struct Request{
            var info: [UIImagePickerController.InfoKey : Any]
        }
        struct Response {
            var image: UIImage
        }
        struct ViewModel {
            var profileImage: UIImage
        }

    }
    
    enum SaveProfileImage {
        struct Request{
            var image: UIImage
        }
        struct Response {
            var error: Error?
        }
        struct ViewModel {
            var profileImage: UIImage
        }

    }

}
