//
//  WelcomeViewController.swift
//  Netflix
//
//  Created by Admin on 8/19/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WelcomeDisplayLogic: AnyObject {}

final class WelcomeViewController: BackgroundImageViewControlller , WelcomeDisplayLogic {
    
    //  MARK:- Clean Components
    var interactor: WelcomeBusinessLogic?
    var router: (NSObjectProtocol & WelcomeRoutingLogic & WelcomeDataPassing)?
    
    //  MARK: @IBOutlet
    @IBOutlet weak var sigInBtn: UIButton! {
        didSet {
            sigInBtn.tintColor = Constants.Design.Color.Primary.White
        }
    }
    @IBOutlet weak var getStaredBtn: UIButton! {
        didSet {
            getStaredBtn.layer.backgroundColor = UIColor(red: 0.824, green: 0.184, blue: 0.149, alpha: 1).cgColor
            getStaredBtn.layer.cornerRadius = 2
            getStaredBtn.tintColor = Constants.Design.Color.Primary.White
            getStaredBtn.titleLabel?.font = Constants.Design.Font.HeadingTwo
        }
    }
    @IBOutlet weak var lb: UILabel! {
        didSet {
            lb.textColor = Constants.Design.Color.Primary.White
            lb.font = UIFont(name: "Helvetica Neue", size: 32)
            lb.textAlignment = .center
        }
    }
    
    @IBOutlet weak var lb2: UILabel! {
        didSet {
            lb2.textColor = Constants.Design.Color.Primary.White
            lb2.font = UIFont(name: "Helvetica Neue", size: 18)
            lb2.textAlignment = .center
        }
    }
    
    //  MARK: Object lifecycle
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    //  MARK: View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        navigationController?.navigationBar.isHidden = true
    }
    
    //  MARK: Setup
    private func setup() {
        let viewController = self
        let interactor = WelcomeInteractor()
        let presenter = WelcomePresenter()
        let router = WelcomeRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    //  MARK:- Button Action
    @IBAction func moveToRegitrationPage(_ sender: Any) {
        guard let tag = (sender as? UIButton)?.tag else { return }
        interactor?.getTappeddButtonTag(requset: Welcome.Save.Request(buttonTag: tag))
        router?.routeToRegistration(segue: nil)
    }
}

