//
//  WelcomeRouter.swift
//  Netflix
//
//  Created by Admin on 8/19/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WelcomeRoutingLogic {
    func routeToRegistration(segue: UIStoryboardSegue?)
}

protocol WelcomeDataPassing {
    var dataStore: WelcomeDataStore? { get }
}

final class WelcomeRouter: NSObject, WelcomeDataPassing {
    
    //  MARK:- Clean Components
    weak var viewController: WelcomeViewController?
    var dataStore: WelcomeDataStore?
}

extension WelcomeRouter: WelcomeRoutingLogic {
    
    //  MARK: Routing
    func routeToRegistration(segue: UIStoryboardSegue?) {
        guard let destinationVC = UIStoryboard.init(name: "Main", bundle: nil)
                .instantiateViewController(withIdentifier: RegistrationViewController.identifier)
                as? RegistrationViewController else { return }
        
        var destinationDS = destinationVC.router!.dataStore!
        passDataToSomewhere(source: dataStore!, destination: &destinationDS)
        navigateToRegistrationPage(source: viewController!, destination: destinationVC)
    }
    
    //  MARK: Navigation
    func navigateToRegistrationPage(source: WelcomeViewController, destination: UIViewController) {
        source.show(destination, sender: nil)
    }
    
    //  MARK: Passing data
    func passDataToSomewhere(source: WelcomeDataStore, destination: inout RegistationDataStore) {
        destination.tag = source.identifier
    }
}
