//
//  WelcomeRouter.swift
//  Netflix
//
//  Created by Admin on 8/19/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol WelcomeRoutingLogic {
    func routeToRegistration(segue: UIStoryboardSegue?)
}

protocol WelcomeDataPassing {
    var dataStore: WelcomeDataStore? { get }
}

class WelcomeRouter: NSObject, WelcomeRoutingLogic, WelcomeDataPassing {
    
    weak var viewController: WelcomeViewController?
    var dataStore: WelcomeDataStore?
    
    // MARK: Routing
    
    func routeToRegistration(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! RegistrationViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
        } else {
            guard let destinationVC = UIStoryboard.init(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "RegistationViewController") as? RegistrationViewController else { return }
            var destinationDS = destinationVC.router!.dataStore!
            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
            navigateToSomewhere(source: viewController!, destination: destinationVC)
        }
    }
    
    // MARK: Navigation
    
    func navigateToSomewhere(source: WelcomeViewController, destination: UIViewController) {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    func passDataToSomewhere(source: WelcomeDataStore, destination: inout RegistationDataStore) {
        destination.tag = source.tag
    }
}
