//
//  SearchResultPresenter.swift
//  Netflix
//
//  Created by Admin on 9/5/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchResultPresentationLogic {
    func presentSearchResult(response: SearchResult.GetSearchResult.Response)
    func presentSelectedMovie(response: SearchResult.MovieDetail.Response)
}

class SearchResultPresenter: SearchResultPresentationLogic {
    
    weak var viewController: SearchResultDisplayLogic?
    
    // MARK: Do something
    
    func presentSearchResult(response: SearchResult.GetSearchResult.Response) {
        let viewModel = SearchResult.GetSearchResult.ViewModel(movieViewModel: response.searchedMoviesDetails.convert())
        viewController?.displaySearchResult(viewModel: viewModel)
    }
    
    func presentSelectedMovie(response: SearchResult.MovieDetail.Response) {
        viewController?.displaySelectedMovie(viewModel: SearchResult.MovieDetail.ViewModel())
    }
    
//    func convert(model: Movies) -> [MovieViewModel] {
//        var movieViewModel = [MovieViewModel]()
//
//        model.details.forEach { movieDetails in
//            let movieModel = MovieViewModel(
//                title: movieDetails.original_title ?? movieDetails.title ?? "unknown Film",
//                posterUrl: movieDetails.poster_path ?? "",
//                id: movieDetails.id ?? -1)
//
//            movieViewModel.append(movieModel)
//        }
//        return movieViewModel
//    }
}
