//
//  SearchResultPresenter.swift
//  Netflix
//
//  Created by Admin on 9/5/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchResultPresentationLogic {
    func presentSearchResult(response: SearchResult.GetSearchResult.Response)
    func presentSelectedMovie(response: SearchResult.GetSelectedMovie.Response)
}

class SearchResultPresenter: SearchResultPresentationLogic {
    
    weak var viewController: SearchResultDisplayLogic?
    
    // MARK: Do something
    
    func presentSearchResult(response: SearchResult.GetSearchResult.Response) {
        let viewModel = SearchResult.GetSearchResult.ViewModel(movieViewModel: response.searchedMoviesDetails?.convert() ?? [])
        viewController?.displaySearchResult(viewModel: viewModel)
    }
    
    func presentSelectedMovie(response: SearchResult.GetSelectedMovie.Response) {
        viewController?.displaySelectedMovie(viewModel: SearchResult.GetSelectedMovie.ViewModel())
    }
}
