//
//  SearchResultModels.swift
//  Netflix
//
//  Created by Admin on 9/5/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SearchResult {
    // MARK: Use cases
    
    enum GetSearchResult {
        struct Request { }
        
        struct Response {
            var searchedMovies: Movies?
        }
        
        struct ViewModel {
            var movieViewModel: [MovieViewModel]
        }
    }
    
    enum GetSelectedMovie {
        struct Request{
            var selectedMovieId: Int
        }
        
        struct Response {}
        
        struct ViewModel {}
    }
}
