//
//  HomePresenter.swift
//  Netflix
//
//  Created by Admin on 8/22/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic {
    func presentMovies(response: Home.MovieInfo.Response)
    func presentSelectedMovie(response: Home.GetSelectedMovie.Response)
}

final class HomePresenter {
    
    weak var viewController: HomeDisplayLogic?
}

extension HomePresenter: HomePresentationLogic {
    
    //  MARK:- HomePresentationLogic Methods
    func presentMovies(response: Home.MovieInfo.Response) {
        
        guard response.error == nil else {
            viewController?.displayAlert(viewModel: Home.Error.ViewModel(errorMessage: response.error!.rawValue))
            return
        }
        viewController?.displayMovies(viewModel: Home.MovieInfo.ViewModel(moviesViewModel: response.movies?.details.convert()))
    }
    
    func presentSelectedMovie(response: Home.GetSelectedMovie.Response) {
        viewController?.displaySelectedMovie(viewModel: Home.GetSelectedMovie.ViewModel())
    }
    
}
