//
//  HomePresenter.swift
//  Netflix
//
//  Created by Admin on 8/22/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic {
    func presentMovies(response: Home.MovieInfo.Response)
}

class HomePresenter: HomePresentationLogic {
    weak var viewController: HomeDisplayLogic?
    
    // MARK: Do something
//    , complition: @escaping (Bool) -> Void
    func presentMovies(response: Home.MovieInfo.Response) {
        var viewModel = Home.MovieInfo.ViewModel()
        switch response.result {
        case .success(let movies):
            viewModel.moviesDetails = movies.details
//            response = Home.MovieInfo.Response(
        case .failure(let error):
            viewModel.error = error.localizedDescription
//            response = Home.MovieInfo.Response(error: error, moviesDetails: nil)
        }
        
//        let viewModel = Home.MovieInfo.ViewModel(error: response.error, moviesDetails: response.moviesDetails)
        viewController?.displayMovies(viewModel: viewModel)
    }
}
