//
//  HomePresenter.swift
//  Netflix
//
//  Created by Admin on 8/22/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic {
    func presentMovies(response: Home.MovieInfo.Response)
    func presentSelectedMovie(response: Home.GetSelectedMovie.Response)
}

final class HomePresenter: HomePresentationLogic {
    
    weak var viewController: HomeDisplayLogic?
    
    // MARK: Do something
    
    func presentMovies(response: Home.MovieInfo.Response) {
        let viewModel = Home.MovieInfo.ViewModel(error: nil, moviesViewModel: (response.movies?.convert())!)
        viewController?.displayMovies(viewModel: viewModel)
    }
    
    func presentSelectedMovie(response: Home.GetSelectedMovie.Response) {
        viewController?.displaySelectedMovie(viewModel: Home.GetSelectedMovie.ViewModel())
    }

}
